require(ape)
require(parallel)
require(rgeos)
require(gpclib)
require(maps)
require(tcltk)
require(diversitree)
require(vegan)
require(phytools)
require(phylolm)
require(phyloch)
require(RADami)
require(geiger)
require(coda)
require(l1ou)
require(phangorn)

require("rgdal") # requires sp, will use proj.4 if installed
require("maptools")
require("ggplot2")
require("plyr")
require('dismo')

if(!exists('label.elements')) source('https://raw.githubusercontent.com/andrew-hipp/morton/master/R/label.elements.R')
if(!exists('haversine')) source('https://raw.githubusercontent.com/andrew-hipp/morton/master/R/haversine.R')
if(!exists('tips.expected')) source('https://raw.githubusercontent.com/andrew-hipp/morton/master/R/tips.expected.R')
if(!exists('summary.by.elements'))   source('https://raw.githubusercontent.com/andrew-hipp/morton/master/R/summary.by.elements.R')
